django_showcase_quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.detail),
    path('<int:question_id>/', views.detail, name='detail'),
    path('end/', views.end, name='end'),
    path('<int:question_id>/check/', views.check, name='check'),
]

quiz/models.py
from django.db import models


class Question(models.Model):
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    correct = models.BooleanField()

    def __str__(self):
        return f'{self.question.text} {self.text}{" ✓" if self.correct else ""}'

quiz/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

from .models import Question, Choice

def detail(request, question_id=None):
    question = Question.objects.earliest('id') if question_id is None else Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'quiz/detail.html', context)

def end(request):
    return render(request, 'quiz/detail.html', {'end': True})

def check(request, question_id):
    choice = Choice.objects.get(id=request.POST['choice'])
    if choice.correct:
        messages.success(request, 'That\'s right!')
    else:
        messages.error(request, 'Wrong!')
    try:
        next_question = Question.objects.filter(id__gt=question_id).earliest('id')
        return HttpResponseRedirect(reverse('quiz:detail', args=(next_question.id,)))
    except Question.DoesNotExist:
        return HttpResponseRedirect(reverse('quiz:end'))
    

quiz/templates/quiz/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Quiz</title>
    <style>
      html {
        background-image: url('https://i.ytimg.com/vi/8S81HQK9nqk/maxresdefault.jpg');
        background-repeat: no-repeat;
        background-position: bottom right;
        min-height: 720px;  /* Image height. */
        background-color: black;
        color: white;
      }
      .success {
        color: green;
      }
      .error {
        color: red;
      }
    </style>
  </head>
  <body>
    <h1>Quiz</h1>
    {% if not end %}
    <h2>{{ question.text }}</h2>
    <form action="{% url 'quiz:check' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <p>
        <input type="radio" name="choice" value="{{ choice.id }}" id="choice{{ forloop.counter }}">
        <label for="choice{{ forloop.counter }}">{{ choice.text }}</label>
      </p>
    {% endfor %}
      <input type="submit" value="Check">
    </form>
    {% else %}
    <h2>THE END</h2>
    {% endif %}
    {% if messages %}
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
  </body>
</html>

quiz/templates/quiz/first.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Quiz</title>
    <style>
      body {
        background-image: url('https://i.ytimg.com/vi/8S81HQK9nqk/maxresdefault.jpg');
        background-repeat: no-repeat;
        background-color: black;
        color: white;
      }
      .success {
        color: green;
      }
      .error {
        color: red;
      }
    </style>
  </head>
  <body>
    <h1>Quiz</h1>
    <h2>{{ first_question.text }}</h2>
    <form action="{% url 'quiz:check' first_question.id %}" method="post">
    {% csrf_token %}
    {% for choice in first_question.choice_set.all %}
      <p>
        <input type="radio" name="choice" value="{{ choice.id }}" id="choice{{ forloop.counter }}">
        <label for="choice{{ forloop.counter }}">{{ choice.text }}</label>
      </p>
    {% endfor %}
    <input type="submit" value="Check">
    </form>
    {% if messages %}
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
  </body>
</html>